# Generated by Django 5.2.3 on 2025-06-17 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(help_text="Identifier for the module, e.g., 'cultural-proverbs'", max_length=100)),
                ('task_id', models.CharField(help_text='Identifier for the specific task or exercise within the module', max_length=100)),
                ('status', models.CharField(choices=[('completed', 'Completed')], default='completed', max_length=20)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Module Progress',
                'verbose_name_plural': 'User Module Progresses',
                'ordering': ['-last_updated_at'],
                'unique_together': {('user', 'module_id', 'task_id')},
            },
        ),
    ]
