# Generated by Django 5.2.3 on 2025-07-09 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTaskAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module_id",
                    models.CharField(
                        db_index=True,
                        help_text="Identifier for the module (e.g., 'cultural-proverbs').",
                        max_length=100,
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        db_index=True,
                        help_text="Identifier for the specific task within the module (e.g., 'beginnerTask4').",
                        max_length=100,
                    ),
                ),
                (
                    "answers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User's answers for the task, stored as a JSON object.",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the last update to these answers.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Task Answer",
                "verbose_name_plural": "User Task Answers",
                "ordering": ["-last_updated"],
                "unique_together": {("user", "module_id", "task_id")},
            },
        ),
    ]
